version: '3.8'
services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
#    image: jenkins/jenkins:${TAG}
    container_name: jenkins
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"


