version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:${TAG}
    container_name: jenkins
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./data:/var/jenkins_home"


